### ISSUE TITLE
How to interpret EPE values in port 1 payload

### ISSUE THREAD

**Issue by tjvandam** [IRNAS/smartparks-rhino-tracker-firmware#30]
The Port 1 messages report EPE value for every GPS fix. As EPE values are not standardized, it would be good to understand the range of EPE value for this device and what can be seen as a good average for normal operation.

**Comment by SloMusti** [comment]
Resolved with https://github.com/IRNAS/smartparks-rhino-tracker-firmware#gps-data in 3a02d4d8febf7bbfdcd0ceecbd724e5085dabade
