### ISSUE TITLE
How to interpret HDOP values in port 1 payload

### ISSUE THREAD

**Issue by tjvandam** [IRNAS/smartparks-rhino-tracker-firmware#31]
Every port 1 payload reports a HDOP value for the GPS fix. It would be good to give the range of this value and explain what a good HDOP value should be with normal operation.

**Comment by SloMusti** [comment]
Resolved with https://github.com/IRNAS/smartparks-rhino-tracker-firmware#gps-data in 3a02d4d8febf7bbfdcd0ceecbd724e5085dabade
