### ISSUE TITLE
Encoder and Decoder are not the same for port 3 settings messages

### ISSUE THREAD

**Issue by tjvandam** [IRNAS/smartparks-rhino-tracker-firmware#39]
Try with: port 3 / hex

`1E 00 88 02 3C 00 03 00 0A 0A C8 00 3C 00 05 32 05 02 00 05 1E 32 8C A0 10 27 00 00 00 00 D0 07 00 00`

Decoder and Encoder both give different results. The JSON settings intended are:

`{
  "fw_version": 256,
  "gps_accel_z_threshold": 0,
  "gps_charge_min": 3000,
  "gps_cold_fix_retry": 2,
  "gps_cold_fix_timeout": 200,
  "gps_fail_retry": 0,
  "gps_hot_fix_retry": 5,
  "gps_hot_fix_timeout": 60,
  "gps_min_ehpe": 50,
  "gps_min_fix_time": 5,
  "gps_periodic_interval": 60,
  "gps_settings": {
    "d3_fix": 1,
    "fail_backoff": 0,
    "fully_resolved": 0,
    "hot_fix": 1
  },
  "gps_triggered_duration": 10,
  "gps_triggered_interval": 3,
  "gps_triggered_threshold": 10,
  "lorawan_datarate_adr": {
    "adr": 0,
    "confirmed_uplink": 0,
    "datarate": 2
  },
  "pulse_min_interval": 0,
  "pulse_on_timeout": 0,
  "pulse_threshold": 0,
  "system_charge_max": 4100,
  "system_charge_min": 3900,
  "system_functions": {
    "accelerometer_enabled": 1,
    "charging_enabled": 1,
    "gps_hot_fix": 0,
    "gps_periodic": 0,
    "gps_triggered": 0,
    "humidity_enabled": 0,
    "light_enabled": 0,
    "temperature_enabled": 0
  },
  "system_input_charge_min": 10000,
  "system_status_interval": 30,
  "system_voltage_interval": 30
}`

The same HEX is DECODED in JSON as:
`{
  "fw_version": 0,
  "gps_accel_z_threshold": 2000,
  "gps_charge_min": 3000,
  "gps_cold_fix_retry": 2,
  "gps_cold_fix_timeout": 200,
  "gps_fail_retry": 0,
  "gps_hot_fix_retry": 5,
  "gps_hot_fix_timeout": 60,
  "gps_min_ehpe": 50,
  "gps_min_fix_time": 5,
  "gps_periodic_interval": 60,
  "gps_settings": {
    "d3_fix": 1,
    "fail_backoff": 0,
    "fully_resolved": 0,
    "hot_fix": 1
  },
  "gps_triggered_duration": 10,
  "gps_triggered_interval": 3,
  "gps_triggered_threshold": 10,
  "lorawan_datarate_adr": {
    "adr": 0,
    "confirmed_uplink": 0,
    "datarate": 2
  },
  "pulse_min_interval": 0,
  "pulse_on_timeout": 0,
  "pulse_threshold": 0,
  "system_charge_max": 4100,
  "system_charge_min": 3900,
  "system_functions": {
    "accelerometer_enabled": 1,
    "charging_enabled": 1,
    "gps_hot_fix": 0,
    "gps_periodic": 0,
    "gps_triggered": 0,
    "humidity_enabled": 0,
    "light_enabled": 0,
    "temperature_enabled": 0
  },
  "system_input_charge_min": 10000,
  "system_status_interval": 30,
  "system_voltage_interval": 30
}`

So issues is with:
  "fw_version": 0,
  "gps_accel_z_threshold": 2000,

**Comment by SloMusti** [comment]
"fw_version": 0, is not an issue, because you can not set the firmware version in json, so the field is always zero. Device reports it when reporting settings.

**Comment by SloMusti** [comment]
This has been resolved in v2.0.0
