### ISSUE TITLE
Add Geoloc / GPS mode

### ISSUE THREAD

**Issue by tjvandam** [IRNAS/smartparks-rhino-tracker-firmware#4]
I would add a Geoloc mote, which means, we can put the tracker in LoRaWAN only mode, so the GPS is not used at all. Then the tracker is essentially a geoloc sensor that only sends regular LoRaWAN packers with a payload that is only minimal with battery voltage and maybe the time between updates. This mode should be easy to activate if for example the power is low and/or the GPS is not working (good enough).

**Comment by SloMusti** [comment]
This is already specified for, GPS can be disabled fully.

**Comment by SloMusti** [comment]
This is achieved by setting the gps_periodic_interval to 0.
