### ISSUE TITLE
gps_on_time_total not reflecting all GPS on time

### ISSUE THREAD

**Issue by tjvandam** [IRNAS/smartparks-rhino-tracker-firmware#40]
It looks like the gps_on_time_total only counts successful GPS fixes, and not accounting for fix tries that fail (time-out). This way we can not estimate battery consumption. Als we can not check if the GPS has actually done all it's retries (hot and cold with their timeout settings).

**Comment by SloMusti** [comment]
This has been resolved in latest v2.0.0 release
