### ISSUE TITLE
Extend GPS logging capability

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/smartparks-rhino-tracker-firmware#46]
Enable persistent and more detailed GPS position logging GPS point (accuracy data, EPE,HDOP,TTF). This must be specified further.

**Comment by tjvandam** [comment]
also add the "motion = 0/1" value. Then we have all valid GPS data in the log.

**Comment by SloMusti** [comment]
There appears to be an option to use 5kB/6kB total of eeprom available for storing values. Current format uses 8bytes per location, however even more data is desired now, meaning this should be compressed or optimized. 

Assume to use 10B per position, then we can fit 500 positions into eeprom. Which at 24h fix interval is about 1.5 years or at 1h interval about 20 days.

**Comment by SloMusti** [comment]
Currently log data is as follows:
```
struct gpsLog_t{
  uint8_t lat1;
  uint8_t lat2;
  uint8_t lat3;
  uint8_t lon1;
  uint8_t lon2;
  uint8_t lon3;
  uint32_t time;
}__attribute__((packed));
```
3 bytes for lat
3 bytes for lon
4 bytes for time of fix - this is wasteful, but what we really care about is minute precision position.

There are 500k minutes per year, 2^24 is 16M and thus this works if we want to do 1m timing precision. 

TTF can fit into say 4 bytes, EPE another 4 bytes as these give a reasonably good idea about the precision

**Comment by SloMusti** [comment]
Implemented in https://github.com/IRNAS/smartparks-rhino-tracker-firmware/releases/tag/v2.0.2
