### ISSUE TITLE
DECODER: Where does the firmware supposed to run

### ISSUE THREAD

**Issue by kronix-dev** [IRNAS/smartparks-rhino-tracker-firmware#49]
should i create a js server for the firmware or it runs on arduino

**Comment by SloMusti** [comment]
This https://github.com/IRNAS/smartparks-rhino-tracker-firmware/blob/master/decoder.js goes to LoRaWAN network server, for example TheThingsNework, see https://learn.adafruit.com/the-things-network-for-feather/payload-decoding
