### ISSUE TITLE
Mismatch timestamp and valid lat/long reported in port 12 message

### ISSUE THREAD

**Issue by tjvandam** [IRNAS/smartparks-rhino-tracker-firmware#51]
I have found a small bug in the timestamp values of the current firmware: a port 12 message reports the last known lat/lon + timestamp. However, when the last GPS attempt has a lat and lon = 0, but a valid timestamp. The next port 12 reports the last known valid lat / lon + the NEW timestamp (which corresponds not to the reported lat/lon, but to the last GPS attempt that resulted in lay/lon = 0). I believe the timestamp value should not be overwritten when lat/lon = 0.

**Comment by SloMusti** [comment]
@tjvandam can you report an example. 

Here the implementation is such that lat/lon/time fields get updated at the same time: https://github.com/IRNAS/smartparks-rhino-tracker-firmware/blob/master/src/gps_tracker.cpp#L558 There does not appear to be an option where these varaibles get updated independently

**Comment by SloMusti** [comment]
Additional checks have been implemented in https://github.com/IRNAS/smartparks-rhino-tracker-firmware/releases/tag/v2.3
