### ISSUE TITLE
No uniform naming of timestamp variable over different ports

### ISSUE THREAD

**Issue by tjvandam** [IRNAS/smartparks-rhino-tracker-firmware#52]
There is a strange thing in the decoders with regards to timestamp variable names, these are not consistent over port 1, port 12 and port 11 messages. It would be better to make these variable names consistent.

You can see the inconsistency - while they should all named the same:
port 1:
decoded.time
decoded.time_decoded

port 12:
decoded.gps_time
decoded.gps_time_decoded

port 11:
location.time
location.time_decoded

**Comment by SloMusti** [comment]
This has been resolved in the release https://github.com/IRNAS/smartparks-rhino-tracker-firmware/releases/tag/v2.3
